title: Welcome to Github!
author: Hartleyosaurus
email: hartleyosaurus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Looking to share code and learn from the community!

# social links
twitter_username: hartleyosaurus # DO NOT include the @ character, or else the build will fail!
github_username:  hartleyosaurus # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

